-- G検定 合格ナビ: Supabase schema
-- Paste this file into the Supabase SQL Editor.
-- It assumes Supabase Auth is enabled and every learning record belongs to auth.users.id.

begin;

-- ---------------------------------------------------------------------------
-- Core user profile
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  exam_date date,
  daily_minutes_goal integer not null default 28
    check (daily_minutes_goal between 0 and 240),
  timezone text not null default 'Asia/Tokyo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is
  'User-owned profile data for the G検定 learning support app.';

-- ---------------------------------------------------------------------------
-- State currently stored in localStorage
-- ---------------------------------------------------------------------------

create table if not exists public.user_learning_state (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  active_view text not null default 'dashboard',
  active_mode text not null default 'all'
    check (active_mode in ('all', 'recall', 'practice', 'explain', 'review')),
  focus_domain text not null default '法律・倫理',
  active_mission_id text,
  practice_cursor jsonb not null default '{}'::jsonb,
  last_opened_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.user_learning_state is
  'One-row app state per user. Mirrors activeMode, focusDomain, activeSession, and practiceCursor.';

-- ---------------------------------------------------------------------------
-- Learning mission progress
-- ---------------------------------------------------------------------------

create table if not exists public.mission_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mission_id text not null,
  domain text,
  mission_type text
    check (mission_type in ('recall', 'practice', 'explain', 'review')),
  status text not null default 'not_started'
    check (status in ('not_started', 'in_progress', 'completed', 'skipped')),
  started_at timestamptz,
  completed_at timestamptz,
  total_minutes integer not null default 0 check (total_minutes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, mission_id)
);

comment on table public.mission_progress is
  'Per-user completion and timing state for each learning mission.';

-- ---------------------------------------------------------------------------
-- Spaced review progress
-- ---------------------------------------------------------------------------

create table if not exists public.review_card_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  review_card_id text not null,
  domain text,
  outcome text check (outcome in ('remembered', 'vague', 'forgot')),
  confidence text check (confidence in ('low', 'medium', 'high')),
  next_due_on date,
  answered_at timestamptz,
  prompt_snapshot text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, review_card_id)
);

comment on table public.review_card_progress is
  'Per-user spaced repetition status for each review card.';

-- ---------------------------------------------------------------------------
-- Practice question attempts
-- ---------------------------------------------------------------------------

create table if not exists public.challenge_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  challenge_id text not null,
  domain text,
  question_snapshot text,
  selected_answer_index integer not null check (selected_answer_index >= 0),
  correct_answer_index integer not null check (correct_answer_index >= 0),
  is_correct boolean generated always as (selected_answer_index = correct_answer_index) stored,
  feedback_snapshot text,
  attempted_at timestamptz not null default now()
);

comment on table public.challenge_attempts is
  'Append-only answer history for practice questions and mini tests.';

-- ---------------------------------------------------------------------------
-- Domain-level progress and weak-point tracking
-- ---------------------------------------------------------------------------

create table if not exists public.domain_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  domain text not null,
  score numeric(5, 2) not null default 0 check (score between 0 and 100),
  confidence_label text,
  weak_reason text,
  next_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, domain)
);

comment on table public.domain_progress is
  'Current readiness score and next action per exam domain.';

-- ---------------------------------------------------------------------------
-- Study sessions and daily aggregates
-- ---------------------------------------------------------------------------

create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  mission_id text,
  domain text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  minutes_spent integer not null default 0 check (minutes_spent >= 0),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

comment on table public.study_sessions is
  'Execution log for user study sessions.';

create table if not exists public.daily_study_stats (
  user_id uuid not null references public.profiles(id) on delete cascade,
  study_date date not null default current_date,
  minutes_spent integer not null default 0 check (minutes_spent >= 0),
  completed_missions_count integer not null default 0 check (completed_missions_count >= 0),
  review_cards_count integer not null default 0 check (review_cards_count >= 0),
  challenge_attempts_count integer not null default 0 check (challenge_attempts_count >= 0),
  correct_challenge_attempts_count integer not null default 0 check (correct_challenge_attempts_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, study_date),
  check (correct_challenge_attempts_count <= challenge_attempts_count)
);

comment on table public.daily_study_stats is
  'Daily summary used for streaks, dashboard charts, and habit tracking.';

-- ---------------------------------------------------------------------------
-- Helpful indexes
-- ---------------------------------------------------------------------------

create index if not exists idx_mission_progress_user_status
  on public.mission_progress (user_id, status);

create index if not exists idx_review_card_progress_user_due
  on public.review_card_progress (user_id, next_due_on);

create index if not exists idx_challenge_attempts_user_attempted
  on public.challenge_attempts (user_id, attempted_at desc);

create index if not exists idx_domain_progress_user_domain
  on public.domain_progress (user_id, domain);

create index if not exists idx_study_sessions_user_started
  on public.study_sessions (user_id, started_at desc);

create index if not exists idx_daily_study_stats_user_date
  on public.daily_study_stats (user_id, study_date desc);

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists set_user_learning_state_updated_at on public.user_learning_state;
create trigger set_user_learning_state_updated_at
  before update on public.user_learning_state
  for each row execute function public.set_updated_at();

drop trigger if exists set_mission_progress_updated_at on public.mission_progress;
create trigger set_mission_progress_updated_at
  before update on public.mission_progress
  for each row execute function public.set_updated_at();

drop trigger if exists set_review_card_progress_updated_at on public.review_card_progress;
create trigger set_review_card_progress_updated_at
  before update on public.review_card_progress
  for each row execute function public.set_updated_at();

drop trigger if exists set_domain_progress_updated_at on public.domain_progress;
create trigger set_domain_progress_updated_at
  before update on public.domain_progress
  for each row execute function public.set_updated_at();

drop trigger if exists set_daily_study_stats_updated_at on public.daily_study_stats;
create trigger set_daily_study_stats_updated_at
  before update on public.daily_study_stats
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Create initial profile/state rows when a Supabase Auth user signs up
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'display_name',
      new.raw_user_meta_data ->> 'name',
      split_part(new.email, '@', 1)
    )
  )
  on conflict (id) do nothing;

  insert into public.user_learning_state (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.user_learning_state enable row level security;
alter table public.mission_progress enable row level security;
alter table public.review_card_progress enable row level security;
alter table public.challenge_attempts enable row level security;
alter table public.domain_progress enable row level security;
alter table public.study_sessions enable row level security;
alter table public.daily_study_stats enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "user_learning_state_manage_own" on public.user_learning_state;
create policy "user_learning_state_manage_own"
  on public.user_learning_state
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "mission_progress_manage_own" on public.mission_progress;
create policy "mission_progress_manage_own"
  on public.mission_progress
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "review_card_progress_manage_own" on public.review_card_progress;
create policy "review_card_progress_manage_own"
  on public.review_card_progress
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "challenge_attempts_manage_own" on public.challenge_attempts;
create policy "challenge_attempts_manage_own"
  on public.challenge_attempts
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "domain_progress_manage_own" on public.domain_progress;
create policy "domain_progress_manage_own"
  on public.domain_progress
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "study_sessions_manage_own" on public.study_sessions;
create policy "study_sessions_manage_own"
  on public.study_sessions
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "daily_study_stats_manage_own" on public.daily_study_stats;
create policy "daily_study_stats_manage_own"
  on public.daily_study_stats
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------------------
-- Grants for Supabase client access. RLS still controls which rows are visible.
-- ---------------------------------------------------------------------------

grant usage on schema public to authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.user_learning_state to authenticated;
grant select, insert, update, delete on public.mission_progress to authenticated;
grant select, insert, update, delete on public.review_card_progress to authenticated;
grant select, insert, update, delete on public.challenge_attempts to authenticated;
grant select, insert, update, delete on public.domain_progress to authenticated;
grant select, insert, update, delete on public.study_sessions to authenticated;
grant select, insert, update, delete on public.daily_study_stats to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
